### ISSUE TITLE
“Memory Error” while fetching feeds from hailataxii service?

### ISSUE THREAD

**Issue by GD-A-150752** [TAXIIProject/libtaxii#236]
I am fetching feeds from **Hailataxii** service using Python's **libtaxii** library. It has 9 feeds, I have successfully fetched 6 feeds but 3 of the feeds are giving me **Memory Error**.

I have run this program on Linux with 15GB RAM, I tracked it for 6 hours and the memory utilization was exceeding and after 12 hours when I checked the progress again, it was displaying **Memory Error**.

```
import libtaxii as t
import libtaxii.messages_11 as tm11
import libtaxii.clients as tc
from libtaxii.common import generate_message_id
from libtaxii.constants import *

RESULTING_FOLDER = 'results'

FEEDS = [
    'Abuse_ch',
    'CyberCrime_Tracker',
    'EmergingThreats_rules',
    'Lehigh_edu',
    'MalwareDomainList_Hostlist',
    'blutmagie_de_torExits',
    'dataForLast_7daysOnly',
    'dshield_BlockList',
    'phishtank_com'
]

USERNAME = 'guest'

PASSWORD = 'guest'


def main(username, password, feeds, result_folder):
    client = tc.HttpClient()
    client.set_auth_type(tc.HttpClient.AUTH_BASIC)
    client.set_auth_credentials({'username': username, 'password': password})
    client.set_use_https(False)

    for feed in feeds:
        print('Start extracting `{}` feed ({}/{})'.format(feed, feeds.index(feed)+1, len(feeds)))
        #print('Start extracting `'+str(feed)+'` feed ('+str(feeds.index(feed)+1)+'/'+str(len(feeds))+')')
        poll_request = tm11.PollRequest(generate_message_id(),
                                        collection_name=feed,
                                        subscription_id=generate_message_id())
        poll_xml = poll_request.to_xml(pretty_print=True)
        http_resp = client.call_taxii_service2('hailataxii.com', '/taxii-data', VID_TAXII_XML_11, poll_xml)
        taxii_message = t.get_message_from_http_response(http_resp, poll_request.message_id)
```

I expected creation of an XML file in results directory because the code after **get_message_from_http_response()** function writes the response in an XML format. All feeds were extracted successfully except blutmagie_de_torExits, dataForLast_7daysOnly and phishtank_com.
Error in console is
```
Traceback (most recent call last): 
 File "hailataxii_feeds_saver.py", line 63, in <module> 
    feeds.feeds_arg, result_folder.result_folder_arg) 
 File "hailataxii_feeds_saver.py", line 31, in main 
    http_resp, poll_request.message_id) 
 File "/home/bscs8/.local/lib/python2.7/site-packages/libtaxii/ init .py", li ne 47, in get_message_from_http_response 
    return get_message_from_urllib_addinfourl(http_response, in_response_to) 
 File "/home/bscs8/.local/lib/python2.7/site-packages/libtaxii/ init .py", li ne 109, in get_message_from_urllib_addinfourl 
    return tmll.get_message_from_xml(response_message, encoding) 
 File "/home/bscs8/.local/lib/python2.7/site-packages/libtaxii/messages_11.py", line 75, in get_message_from_xml 
    xml_string = xml_string.decode(encoding, 'replace') 
 File "/usr/lib/python2.7/encodings/utf_8.py", line 16, in decode 
    return codecs.utf_8_decode(input, errors, True) 
MemoryError 
```

**Comment by emmanvg** [comment]
@GD-A-150752, I don't think there is an easy fix here. The file you are downloading potentially GB in size will reach
```
File "/home/bscs8/.local/lib/python2.7/site-packages/libtaxii/messages_11.py", line 75, in get_message_from_xml 
    xml_string = xml_string.decode(encoding, 'replace')
```
where essentially you request a similar amount of memory to allocate the result of this operation (since Python strings are immutable). Afterwards, this value will be parsed by LXML that will again request a huge amount of memory to represent this string as an `etree` instance.

**Comment by GD-A-150752** [comment]
Thank you @emmanvg for your response.
I have changed my server and now I have created VM instance in **Google Cloud** that is _Linux Debian, with vCPU-4, 52GB RAM and 20 GB hard disk._
I am downloading **phishTank** feed and it has been more than 20 hours now, my server is still showing CPU and Disk I/O activity.
I am unable to log into WinScp or Google Cloud shell terminal to monitor **htop** because it gives me connection timeout error (due to heavy activity on memory).
Can you please devise another solution to download the feed?
Can you mention the estimated size of the feed?

**Comment by emmanvg** [comment]
@GD-A-150752 I have no control over the content hosted at hailataxii, I would contact them directly for that type of questions.

The other thing you can try is using Asynchronous Requests, which requires using the API objects to create your specialized request. That way you may at least save portions of the request. If you need all the data then this might be unfeasible.

**Comment by clenk** [comment]
@GD-A-150752 I'm closing this due to inactivity, but feel free to reopen if necessary.
